In [1]:
import pandas as pd
import numpy as np

import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

In [2]:
input_file = "./OriginData/水位数据20241015.xlsx"
out_file = "./OutputData/merged_涌水量水位.xlsx"

In [3]:
# 读取Excel文件中的所有sheets
datas = pd.read_excel(input_file, sheet_name=None)

In [4]:
datas

{'SBZK 670-118-1':            位置点 Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4
 0     横坐标（经纬度）        纵坐标  高程（终孔，井底）                   案例      水位（m)
 1    3045453.7   401240.1      671.2  2022-12-21 00:00:00        622
 2    3045453.7   401240.1      671.2  2022-12-22 00:00:00        NaN
 3    3045453.7   401240.1      671.2  2022-12-23 00:00:00        NaN
 4    3045453.7   401240.1      671.2  2022-12-24 00:00:00        NaN
 ..         ...        ...        ...                  ...        ...
 504  3045453.7   401240.1      671.2  2024-05-07 00:00:00    470.394
 505  3045453.7   401240.1      671.2  2024-05-08 00:00:00    470.046
 506  3045453.7   401240.1      671.2  2024-05-09 00:00:00    469.835
 507  3045453.7   401240.1      671.2  2024-05-10 00:00:00    469.534
 508  3045453.7   401240.1      671.2  2024-05-11 00:00:00    469.154

 [509 rows x 5 columns],
 'SBZK670-110-1':           位置点 Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4
 0    横坐标（经纬度）        纵坐标  高程（终孔，井底）                   案例      水位（m)
 1   3045315.4   401156.7      670.7  2024-04-06 00:00:00    632.028
 2   3045315.4   401156.7      670.7  2024-04-07 00:00:00    631.001
 3   3045315.4   401156.7      670.7  2024-04-08 00:00:00     630.71
 4   3045315.4   401156.7      670.7  2024-04-09 00:00:00     630.01
 5   3045315.4   401156.7      670.7  2024-04-10 00:00:00    629.422
 6   3045315.4   401156.7      670.7  2024-04-11 00:00:00    628.817
 7   3045315.4   401156.7      670.7  2024-04-12 00:00:00    628.369
 8   3045315.4   401156.7      670.7  2024-04-13 00:00:00    627.842
 9   3045315.4   401156.7      670.7  2024-04-14 00:00:00        NaN
 10  3045315.4   401156.7      670.7  2024-04-15 00:00:00        NaN
 11  3045315.4   401156.7      670.7  2024-04-16 00:00:00        NaN
 12  3045315.4   401156.7      670.7  2024-04-17 00:00:00        NaN
 13  3045315.4   401156.7      670.7  2024-04-18 00:00:00        NaN
 14  3045315.4   401156.7      670.7  2024-04-19 00:00:00    627.842
 15  3045315.4   401156.7      670.7  2024-04-20 00:00:00        NaN
 16  3045315.4   401156.7      670.7  2024-04-21 00:00:00        NaN
 17  3045315.4   401156.7      670.7  2024-04-22 00:00:00    623.289
 18  3045315.4   401156.7      670.7  2024-04-23 00:00:00    622.805
 19  3045315.4   401156.7      670.7  2024-04-24 00:00:00    622.148
 20  3045315.4   401156.7      670.7  2024-04-25 00:00:00    621.694
 21  3045315.4   401156.7      670.7  2024-04-26 00:00:00    620.991
 22  3045315.4   401156.7      670.7  2024-04-27 00:00:00    620.568
 23  3045315.4   401156.7      670.7  2024-04-28 00:00:00    620.056
 24  3045315.4   401156.7      670.7  2024-04-29 00:00:00    619.782
 25  3045315.4   401156.7      670.7  2024-04-30 00:00:00    619.634
 26  3045315.4   401156.7      670.7  2024-05-01 00:00:00    619.235
 27  3045315.4   401156.7      670.7  2024-05-02 00:00:00    618.889
 28  3045315.4   401156.7      670.7  2024-05-03 00:00:00    619.802
 29  3045315.4   401156.7      670.7  2024-05-04 00:00:00    619.441
 30  3045315.4   401156.7      670.7  2024-05-05 00:00:00    618.821
 31  3045315.4   401156.7      670.7  2024-05-06 00:00:00     618.79
 32  3045315.4   401156.7      670.7  2024-05-07 00:00:00    618.168
 33  3045315.4   401156.7      670.7  2024-05-08 00:00:00     617.74
 34  3045315.4   401156.7      670.7  2024-05-09 00:00:00    617.292
 35  3045315.4   401156.7      670.7  2024-05-10 00:00:00    616.957
 36  3045315.4   401156.7      670.7  2024-05-11 00:00:00    616.356,
 'ZK001':            位置点 Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4
 0     横坐标（经纬度）        纵坐标  高程（终孔，井底）                   案例      水位（m)
 1      3045651   400574.9      670.2  2020-05-28 00:00:00    868.386
 2      3045651   400574.9      670.2  2020-05-29 00:00:00        NaN
 3      3045651   400574.9      670.2  2020-05-30 00:00:00    861.966
 4      3045651   400574.9      670.2  2020-05-31 00:00:00        NaN
 ...        ...        ...        ...                  ...        ...
 1441   3045651   400574.9      670.2  2024-05-07 00:00:00    611.178
 1442   3045651   400574.9      670.2  2024-05-08 00:00:00    610.613
 1443   3045651   400574.9      670.2  2024-05-09 00:00:00    610.351
 1444   3045651   400574.9      670.2  2024-05-10 00:00:00        NaN
 1445   3045651   400574.9      670.2  2024-05-11 00:00:00        NaN

 [1446 rows x 5 columns],
 'DK06':            位置点    Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4  \
 0          横坐标           纵坐标  高程（终孔，井底）                   案例      水位（m)
 1    3044758.5  35401368.965    905.534  2023-01-01 00:00:00        NaN
 2    3044758.5  35401368.965    905.534  2023-01-02 00:00:00        NaN
 3    3044758.5  35401368.965    905.534  2023-01-03 00:00:00        NaN
 4    3044758.5  35401368.965    905.534  2023-01-04 00:00:00        NaN
 ..         ...           ...        ...                  ...        ...
 493  3044758.5  35401368.965    905.534  2024-05-07 00:00:00    845.848
 494  3044758.5  35401368.965    905.534  2024-05-08 00:00:00    845.377
 495  3044758.5  35401368.965    905.534  2024-05-09 00:00:00    844.926
 496  3044758.5  35401368.965    905.534  2024-05-10 00:00:00    844.848
 497  3044758.5  35401368.965    905.534  2024-05-11 00:00:00    844.655

        Unnamed: 5
 0              备注
 1    数据从2023年开始记录
 2             NaN
 3             NaN
 4             NaN
 ..            ...
 493           NaN
 494           NaN
 495           NaN
 496           NaN
 497           NaN

 [498 rows x 6 columns],
 'BK01':               位置点    Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4
 0             横坐标           纵坐标  高程（终孔，井底）                   案例      水位（m)
 1     3045731.833  35400157.971    891.566  2020-01-01 00:00:00     875.47
 2     3045731.833  35400157.971    891.566  2020-01-02 00:00:00     875.42
 3     3045731.833  35400157.971    891.566  2020-01-03 00:00:00     875.37
 4     3045731.833  35400157.971    891.566  2020-01-04 00:00:00     875.52
 ...           ...           ...        ...                  ...        ...
 1589  3045731.833  35400157.971    891.566  2024-05-07 00:00:00    887.075
 1590  3045731.833  35400157.971    891.566  2024-05-08 00:00:00    887.141
 1591  3045731.833  35400157.971    891.566  2024-05-09 00:00:00    887.172
 1592  3045731.833  35400157.971    891.566  2024-05-10 00:00:00    887.251
 1593  3045731.833  35400157.971    891.566  2024-05-11 00:00:00    887.247

 [1594 rows x 5 columns],
 'BK11':               位置点    Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4  \
 0             横坐标           纵坐标  高程（终孔，井底）                   案例      水位（m)
 1     3045103.988  35401268.816    907.163  2020-01-01 00:00:00        NaN
 2     3045103.988  35401268.816    907.163  2020-01-02 00:00:00        NaN
 3     3045103.988  35401268.816    907.163  2020-01-03 00:00:00        NaN
 4     3045103.988  35401268.816    907.163  2020-01-04 00:00:00        NaN
 ...           ...           ...        ...                  ...        ...
 1589  3045103.988  35401268.816    907.163  2024-05-07 00:00:00    693.221
 1590  3045103.988  35401268.816    907.163  2024-05-08 00:00:00    693.087
 1591  3045103.988  35401268.816    907.163  2024-05-09 00:00:00    692.922
 1592  3045103.988  35401268.816    907.163  2024-05-10 00:00:00    692.788
 1593  3045103.988  35401268.816    907.163  2024-05-11 00:00:00    692.111

      Unnamed: 5
 0           NaN
 1           NaN
 2           NaN
 3           NaN
 4           NaN
 ...         ...
 1589        NaN
 1590        NaN
 1591        NaN
 1592        NaN
 1593        NaN

 [1594 rows x 6 columns],
 'SK01':               位置点  Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4  \
 0             横坐标         纵坐标  高程（终孔，井底）                   案例      水位（m)
 1    30456 19.868  400271.422     670.16  2023-01-01 00:00:00        NaN
 2    30457 19.868  400271.422     670.16  2023-01-02 00:00:00        NaN
 3    30458 19.868  400271.422     670.16  2023-01-03 00:00:00        NaN
 4    30459 19.868  400271.422     670.16  2023-01-04 00:00:00        NaN
 ..            ...         ...        ...                  ...        ...
 493  30948 19.868  400271.422     670.16  2024-05-07 00:00:00    615.061
 494  30949 19.868  400271.422     670.16  2024-05-08 00:00:00    620.726
 495  30950 19.868  400271.422     670.16  2024-05-09 00:00:00    622.284
 496  30951 19.868  400271.422     670.16  2024-05-10 00:00:00    623.195
 497  30952 19.868  400271.422     670.16  2024-05-11 00:00:00    612.423

             Unnamed: 5
 0                  NaN
 1    水位数据于2023年10月开始记录
 2                  NaN
 3                  NaN
 4                  NaN
 ..                 ...
 493                NaN
 494                NaN
 495                NaN
 496                NaN
 497                NaN

 [498 rows x 6 columns],
 'SK02':              位置点 Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4  \
 0            横坐标        纵坐标  高程（终孔，井底）                   案例      水位（m)
 1    3045444.532  399788505     611.54  2023-01-01 00:00:00        NaN
 2    3045444.532  399788505     611.54  2023-01-02 00:00:00        NaN
 3    3045444.532  399788505     611.54  2023-01-03 00:00:00        NaN
 4    3045444.532  399788505     611.54  2023-01-04 00:00:00        NaN
 ..           ...        ...        ...                  ...        ...
 493  3045444.532  399788505     611.54  2024-05-07 00:00:00     449.05
 494  3045444.532  399788505     611.54  2024-05-08 00:00:00    449.035
 495  3045444.532  399788505     611.54  2024-05-09 00:00:00     449.05
 496  3045444.532  399788505     611.54  2024-05-10 00:00:00    449.114
 497  3045444.532  399788505     611.54  2024-05-11 00:00:00     448.99

            Unnamed: 5
 0                 NaN
 1    水位数据于2023年4月开始记录
 2                 NaN
 3                 NaN
 4                 NaN
 ..                ...
 493               NaN
 494               NaN
 495               NaN
 496               NaN
 497               NaN

 [498 rows x 6 columns],
 'SK03':              位置点  Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4  \
 0            横坐标         纵坐标  高程（终孔，井底）                   案例      水位（m)
 1    3045348.099  398913.477     612.32  2023-01-01 00:00:00        NaN
 2    3045348.099  398913.477     612.32  2023-01-02 00:00:00        NaN
 3    3045348.099  398913.477     612.32  2023-01-03 00:00:00        NaN
 4    3045348.099  398913.477     612.32  2023-01-04 00:00:00        NaN
 ..           ...         ...        ...                  ...        ...
 493  3045348.099  398913.477     612.32  2024-05-07 00:00:00    608.026
 494  3045348.099  398913.477     612.32  2024-05-08 00:00:00    608.139
 495  3045348.099  398913.477     612.32  2024-05-09 00:00:00    608.193
 496  3045348.099  398913.477     612.32  2024-05-10 00:00:00    608.266
 497  3045348.099  398913.477     612.32  2024-05-11 00:00:00    608.261

             Unnamed: 5
 0                  NaN
 1    水位数据于2023年10月开始记录
 2                  NaN
 3                  NaN
 4                  NaN
 ..                 ...
 493                NaN
 494                NaN
 495                NaN
 496                NaN
 497                NaN

 [498 rows x 6 columns],
 'SK04':              位置点  Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4
 0            横坐标         纵坐标  高程（终孔，井底）                   案例      水位（m)
 1    3045042.366  399117.761     610.38  2023-01-01 00:00:00        NaN
 2    3045042.366  399117.761     610.38  2023-01-02 00:00:00        NaN
 3    3045042.366  399117.761     610.38  2023-01-03 00:00:00        NaN
 4    3045042.366  399117.761     610.38  2023-01-04 00:00:00        NaN
 ..           ...         ...        ...                  ...        ...
 493  3045042.366  399117.761     610.38  2024-05-07 00:00:00    663.214
 494  3045042.366  399117.761     610.38  2024-05-08 00:00:00    663.414
 495  3045042.366  399117.761     610.38  2024-05-09 00:00:00    663.514
 496  3045042.366  399117.761     610.38  2024-05-10 00:00:00    663.714
 497  3045042.366  399117.761     610.38  2024-05-11 00:00:00    663.814

 [498 rows x 5 columns],
 'SK05':              位置点  Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4
 0            横坐标         纵坐标  高程（终孔，井底）                   案例      水位（m)
 1    3045111.715  399697.412     673.69  2023-01-01 00:00:00        NaN
 2    3045111.715  399697.412     673.69  2023-01-02 00:00:00        NaN
 3    3045111.715  399697.412     673.69  2023-01-03 00:00:00        NaN
 4    3045111.715  399697.412     673.69  2023-01-04 00:00:00        NaN
 ..           ...         ...        ...                  ...        ...
 493  3045111.715  399697.412     673.69  2024-05-07 00:00:00    635.689
 494  3045111.715  399697.412     673.69  2024-05-08 00:00:00    635.569
 495  3045111.715  399697.412     673.69  2024-05-09 00:00:00    635.457
 496  3045111.715  399697.412     673.69  2024-05-10 00:00:00      635.4
 497  3045111.715  399697.412     673.69  2024-05-11 00:00:00    635.224

 [498 rows x 5 columns],
 'SK06':              位置点     Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4  \
 0            横坐标            纵坐标  高程（终孔，井底）                   案例      水位（m)
 1    3045156.773   400313. .556    1028.97  2023-01-01 00:00:00        NaN
 2    3045157.773   400313. .557    1029.97  2023-01-02 00:00:00        NaN
 3    3045158.773   400313. .558    1030.97  2023-01-03 00:00:00        NaN
 4    3045159.773   400313. .559    1031.97  2023-01-04 00:00:00        NaN
 ..           ...            ...        ...                  ...        ...
 493  3045648.773  400313. .1048    1520.97  2024-05-07 00:00:00    981.755
 494  3045649.773  400313. .1049    1521.97  2024-05-08 00:00:00    981.744
 495  3045650.773  400313. .1050    1522.97  2024-05-09 00:00:00    981.734
 496  3045651.773  400313. .1051    1523.97  2024-05-10 00:00:00    981.778
 497  3045652.773  400313. .1052    1524.97  2024-05-11 00:00:00    981.756

        Unnamed: 5
 0             NaN
 1    从2023年4月开始记录
 2             NaN
 3             NaN
 4             NaN
 ..            ...
 493           NaN
 494           NaN
 495           NaN
 496           NaN
 497           NaN

 [498 rows x 6 columns],
 'SK07':              位置点  Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4  \
 0            横坐标         纵坐标  高程（终孔，井底）                   案例      水位（m)
 1    3045804 467  399757.297     913.75  2022-12-07 00:00:00     911.64
 2    3045804 468  399757.297     913.75  2022-12-08 00:00:00        NaN
 3    3045804 469  399757.297     913.75  2022-12-09 00:00:00        NaN
 4    3045804 470  399757.297     913.75  2022-12-10 00:00:00        NaN
 ..           ...         ...        ...                  ...        ...
 518  3045804 984  399757.297     913.75  2024-05-07 00:00:00    883.862
 519  3045804 985  399757.297     913.75  2024-05-08 00:00:00    884.107
 520  3045804 986  399757.297     913.75  2024-05-09 00:00:00    884.153
 521  3045804 987  399757.297     913.75  2024-05-10 00:00:00    884.367
 522  3045804 988  399757.297     913.75  2024-05-11 00:00:00     884.29

          Unnamed: 5
 0               NaN
 1    水位从2022年7月开始记录
 2               NaN
 3               NaN
 4               NaN
 ..              ...
 518             NaN
 519             NaN
 520             NaN
 521             NaN
 522             NaN

 [523 rows x 6 columns],
 'SK08':              位置点  Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4  \
 0       横坐标（经纬度）         纵坐标  高程（终孔，井底）                   案例      水位（m)
 1    3046212 296  399483.556   926. .20  2022-12-07 00:00:00     903.52
 2    3046212 297  399484.556   926. .21  2022-12-08 00:00:00        NaN
 3    3046212 298  399485.556   926. .22  2022-12-09 00:00:00        NaN
 4    3046212 299  399486.556   926. .23  2022-12-10 00:00:00        NaN
 ..           ...         ...        ...                  ...        ...
 518  3046212 813  400000.556  926. .537  2024-05-07 00:00:00    901.915
 519  3046212 814  400001.556  926. .538  2024-05-08 00:00:00    902.427
 520  3046212 815  400002.556  926. .539  2024-05-09 00:00:00    902.534
 521  3046212 816  400003.556  926. .540  2024-05-10 00:00:00     902.84
 522  3046212 817  400004.556  926. .541  2024-05-11 00:00:00    902.805

           Unnamed: 5
 0                NaN
 1    水位于2022年12月开始记录
 2                NaN
 3                NaN
 4                NaN
 ..               ...
 518              NaN
 519              NaN
 520              NaN
 521              NaN
 522              NaN

 [523 rows x 6 columns],
 'SK09':             位置点  Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4  \
 0      横坐标（经纬度）         纵坐标  高程（终孔，井底）                   案例      水位（m)
 1    3045730461  398843.511     941.53  2023-01-01 00:00:00        NaN
 2    3045730461  398843.511     941.53  2023-01-02 00:00:00        NaN
 3    3045730461  398843.511     941.53  2023-01-03 00:00:00        NaN
 4    3045730461  398843.511     941.53  2023-01-04 00:00:00        NaN
 ..          ...         ...        ...                  ...        ...
 493  3045730461  398843.511     941.53  2024-05-07 00:00:00    909.628
 494  3045730461  398843.511     941.53  2024-05-08 00:00:00    909.774
 495  3045730461  398843.511     941.53  2024-05-09 00:00:00    910.064
 496  3045730461  398843.511     941.53  2024-05-10 00:00:00    910.356
 497  3045730461  398843.511     941.53  2024-05-11 00:00:00    910.035

        Unnamed: 5
 0             NaN
 1    水位于2023年开始记录
 2             NaN
 3             NaN
 4             NaN
 ..            ...
 493           NaN
 494           NaN
 495           NaN
 496           NaN
 497           NaN

 [498 rows x 6 columns],
 'SK14':            位置点 Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4  \
 0     横坐标（经纬度）        纵坐标  高程（终孔，井底）                   案例      水位（m)
 1    304537741   40127407     670.61  2023-06-28 00:00:00        715
 2    304537741   40127407     670.61  2023-06-29 00:00:00        NaN
 3    304537741   40127407     670.61  2023-06-30 00:00:00        NaN
 4    304537741   40127407     670.61  2023-07-01 00:00:00        NaN
 ..         ...        ...        ...                  ...        ...
 315  304537741   40127407     670.61  2024-05-07 00:00:00     679.34
 316  304537741   40127407     670.61  2024-05-08 00:00:00     679.04
 317  304537741   40127407     670.61  2024-05-09 00:00:00     678.84
 318  304537741   40127407     670.61  2024-05-10 00:00:00     678.54
 319  304537741   40127407     670.61  2024-05-11 00:00:00     678.44

          Unnamed: 5
 0               NaN
 1    水位于2023年6月开始记录
 2               NaN
 3               NaN
 4               NaN
 ..              ...
 315             NaN
 316             NaN
 317             NaN
 318             NaN
 319             NaN

 [320 rows x 6 columns],
 'SK15':              位置点  Unnamed: 1 Unnamed: 2             时间是具体时间点 Unnamed: 4  \
 0       横坐标（经纬度）         纵坐标  高程（终孔，井底）                   案例      水位（m)
 1    3045833.438  401067.686      614.4  2023-12-01 00:00:00        NaN
 2    3045833.438  401067.686      614.4  2023-12-02 00:00:00        NaN
 3    3045833.438  401067.686      614.4  2023-12-03 00:00:00        NaN
 4    3045833.438  401067.686      614.4  2023-12-04 00:00:00        NaN
 ..           ...         ...        ...                  ...        ...
 159  3045833.438  401067.686      614.4  2024-05-07 00:00:00        NaN
 160  3045833.438  401067.686      614.4  2024-05-08 00:00:00        NaN
 161  3045833.438  401067.686      614.4  2024-05-09 00:00:00        NaN
 162  3045833.438  401067.686      614.4  2024-05-10 00:00:00        NaN
 163  3045833.438  401067.686      614.4  2024-05-11 00:00:00        NaN

           Unnamed: 5
 0                NaN
 1    水位于2023年12月开始记录
 2                NaN
 3                NaN
 4                NaN
 ..               ...
 159              NaN
 160              NaN
 161              NaN
 162              NaN
 163              NaN


In [5]:
# 将所有sheets合并成一个DataFrame
df = pd.concat(datas.values())
df = df.drop(df.columns[-1], axis=1)
df = df.drop(0, axis=0)
df.columns = ["经度","纬度","高程","日期","水位"]
# 1. 将日期列转换为 datetime 类型，无法解析的设为 NaT
df['日期'] = pd.to_datetime(df['日期'], errors='coerce')  
# 2. 删除日期为 NaT（不规范）的行
df = df.dropna(subset=['日期'])  
df['水位'] = pd.to_numeric(df['水位'], errors='coerce')
df['经度'] = pd.to_numeric(df['经度'], errors='coerce')
df['纬度'] = pd.to_numeric(df['纬度'], errors='coerce')
df['高程'] = pd.to_numeric(df['高程'], errors='coerce')
df = df.dropna(subset=['水位'])  
df = df.dropna(subset=['经度'])
df = df.dropna(subset=['纬度'])
df = df.dropna(subset=['高程']) 
df.dropna()

              经度            纬度       高程         日期       水位
1    3045453.700  4.012401e+05  671.200 2022-12-21  622.000
8    3045453.700  4.012401e+05  671.200 2022-12-28  618.700
14   3045453.700  4.012401e+05  671.200 2023-01-03  614.500
20   3045453.700  4.012401e+05  671.200 2023-01-09  611.600
29   3045453.700  4.012401e+05  671.200 2023-01-18  610.000
..           ...           ...      ...        ...      ...
799  3044799.788  3.540080e+07  904.286 2024-05-07  753.971
800  3044799.788  3.540080e+07  904.286 2024-05-08  753.967
801  3044799.788  3.540080e+07  904.286 2024-05-09  753.830
802  3044799.788  3.540080e+07  904.286 2024-05-10  753.278
803  3044799.788  3.540080e+07  904.286 2024-05-11  752.937

[10514 rows x 5 columns]

In [6]:
df

              经度            纬度       高程         日期       水位
1    3045453.700  4.012401e+05  671.200 2022-12-21  622.000
8    3045453.700  4.012401e+05  671.200 2022-12-28  618.700
14   3045453.700  4.012401e+05  671.200 2023-01-03  614.500
20   3045453.700  4.012401e+05  671.200 2023-01-09  611.600
29   3045453.700  4.012401e+05  671.200 2023-01-18  610.000
..           ...           ...      ...        ...      ...
799  3044799.788  3.540080e+07  904.286 2024-05-07  753.971
800  3044799.788  3.540080e+07  904.286 2024-05-08  753.967
801  3044799.788  3.540080e+07  904.286 2024-05-09  753.830
802  3044799.788  3.540080e+07  904.286 2024-05-10  753.278
803  3044799.788  3.540080e+07  904.286 2024-05-11  752.937

[10514 rows x 5 columns]

In [7]:
# 确保时间列是datetime类型
df['日期'] = pd.to_datetime(df['日期'])
grouped = df.groupby(['经度', '纬度', '高程'])
# 现在grouped是一个GroupBy对象，你可以遍历它，或者对每个组进行操作
df_list = []
for name, group in grouped:
    print("group type : ",type(group))
    # 首先将'日期'列设置为索引
    group.set_index('日期', inplace=True)
    
    # 确保时间序列是完整的，使用resample方法来按所需的时间频率填充缺失的时间点
    df_resampled = group.resample('D').mean()
    
    # 使用线性插值来填充缺失的数据
    df_interpolated = df_resampled.interpolate(method='linear')
    
    # 索引重置为列
    df_interpolated.reset_index(inplace=True)

    #将插值后的数据加入
    df_list.append(df_interpolated)

    print(f"Group: {name}")
    print(df_interpolated)

# 使用pd.concat将列表中的所有DataFrame合并成一个单一的DataFrame
df_linear = pd.concat(df_list, ignore_index=True)
df_linear = df_linear.round(3)

group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3044699.547, 401076.749, 905.05)
            日期           经度          纬度      高程       水位
0   2023-03-31  3044699.547  401076.749  905.05  865.482
1   2023-04-01  3044699.547  401076.749  905.05  866.392
2   2023-04-02  3044699.547  401076.749  905.05  867.302
3   2023-04-03  3044699.547  401076.749  905.05  868.212
4   2023-04-04  3044699.547  401076.749  905.05  869.122
..         ...          ...         ...     ...      ...
403 2024-05-07  3044699.547  401076.749  905.05  853.677
404 2024-05-08  3044699.547  401076.749  905.05  853.595
405 2024-05-09  3044699.547  401076.749  905.05  853.582
406 2024-05-10  3044699.547  401076.749  905.05  853.625
407 2024-05-11  3044699.547  401076.749  905.05  853.476

[408 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3044705.773, 400634.262, 902.88)
            日期           经度          纬度      高程       水位
0   2023-02-02  3044705.773  400634.262  902.88  841.617
1   2023-02-03  3044705.773  400634.262  902.88  841.987
2   2023-02-04  3044705.773  400634.262  902.88  842.357
3   2023-02-05  3044705.773  400634.262  902.88  842.727
4   2023-02-06  3044705.773  400634.262  902.88  843.097
..         ...          ...         ...     ...      ...
460 2024-05-07  3044705.773  400634.262  902.88  857.847
461 2024-05-08  3044705.773  400634.262  902.88  857.792
462 2024-05-09  3044705.773  400634.262  902.88  857.743
463 2024-05-10  3044705.773  400634.262  902.88  857.786
464 2024-05-11  3044705.773  400634.262  902.88  857.654

[465 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3044758.5, 35401368.965, 905.534)
            日期         经度            纬度       高程       水位
0   2023-01-05  3044758.5  3.540137e+07  905.534  902.630
1   2023-01-06  3044758.5  3.540137e+07  905.534  902.454
2   2023-01-07  3044758.5  3.540137e+07  905.534  902.278
3   2023-01-08  3044758.5  3.540137e+07  905.534  902.102
4   2023-01-09  3044758.5  3.540137e+07  905.534  901.926
..         ...        ...           ...      ...      ...
488 2024-05-07  3044758.5  3.540137e+07  905.534  845.848
489 2024-05-08  3044758.5  3.540137e+07  905.534  845.377
490 2024-05-09  3044758.5  3.540137e+07  905.534  844.926
491 2024-05-10  3044758.5  3.540137e+07  905.534  844.848
492 2024-05-11  3044758.5  3.540137e+07  905.534  844.655

[493 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3044799.788, 35400795.008, 904.286)
            日期           经度            纬度       高程       水位
0   2022-03-07  3044799.788  3.540080e+07  904.286  832.886
1   2022-03-08  3044799.788  3.540080e+07  904.286  832.646
2   2022-03-09  3044799.788  3.540080e+07  904.286  832.406
3   2022-03-10  3044799.788  3.540080e+07  904.286  832.166
4   2022-03-11  3044799.788  3.540080e+07  904.286  831.926
..         ...          ...           ...      ...      ...
792 2024-05-07  3044799.788  3.540080e+07  904.286  753.971
793 2024-05-08  3044799.788  3.540080e+07  904.286  753.967
794 2024-05-09  3044799.788  3.540080e+07  904.286  753.830
795 2024-05-10  3044799.788  3.540080e+07  904.286  753.278
796 2024-05-11  3044799.788  3.540080e+07  904.286  752.937

[797 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3044878.823, 35401272.521, 905.391)
            日期           经度            纬度       高程       水位
0   2021-11-22  3044878.823  3.540127e+07  905.391  758.391
1   2021-11-23  3044878.823  3.540127e+07  905.391  758.351
2   2021-11-24  3044878.823  3.540127e+07  905.391  758.311
3   2021-11-25  3044878.823  3.540127e+07  905.391  758.271
4   2021-11-26  3044878.823  3.540127e+07  905.391  758.231
..         ...          ...           ...      ...      ...
897 2024-05-07  3044878.823  3.540127e+07  905.391  698.311
898 2024-05-08  3044878.823  3.540127e+07  905.391  697.910
899 2024-05-09  3044878.823  3.540127e+07  905.391  697.636
900 2024-05-10  3044878.823  3.540127e+07  905.391  697.217
901 2024-05-11  3044878.823  3.540127e+07  905.391  695.142

[902 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045042.366, 399117.761, 610.38)
            日期           经度          纬度      高程       水位
0   2023-01-10  3045042.366  399117.761  610.38  631.000
1   2023-01-11  3045042.366  399117.761  610.38  631.000
2   2023-01-12  3045042.366  399117.761  610.38  631.000
3   2023-01-13  3045042.366  399117.761  610.38  631.000
4   2023-01-14  3045042.366  399117.761  610.38  631.000
..         ...          ...         ...     ...      ...
483 2024-05-07  3045042.366  399117.761  610.38  663.214
484 2024-05-08  3045042.366  399117.761  610.38  663.414
485 2024-05-09  3045042.366  399117.761  610.38  663.514
486 2024-05-10  3045042.366  399117.761  610.38  663.714
487 2024-05-11  3045042.366  399117.761  610.38  663.814

[488 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045084.549, 35401418.175, 907.26)
            日期           经度            纬度      高程         水位
0   2021-12-30  3045084.549  3.540142e+07  907.26  784.84000
1   2021-12-31  3045084.549  3.540142e+07  907.26  784.82375
2   2022-01-01  3045084.549  3.540142e+07  907.26  784.80750
3   2022-01-02  3045084.549  3.540142e+07  907.26  784.79125
4   2022-01-03  3045084.549  3.540142e+07  907.26  784.77500
..         ...          ...           ...     ...        ...
859 2024-05-07  3045084.549  3.540142e+07  907.26  721.57000
860 2024-05-08  3045084.549  3.540142e+07  907.26  721.34600
861 2024-05-09  3045084.549  3.540142e+07  907.26  721.20400
862 2024-05-10  3045084.549  3.540142e+07  907.26  721.10800
863 2024-05-11  3045084.549  3.540142e+07  907.26  720.63200

[864 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045103.988, 35401268.816, 907.163)
             日期           经度            纬度       高程          水位
0    2020-01-23  3045103.988  3.540127e+07  907.163  777.660000
1    2020-01-24  3045103.988  3.540127e+07  907.163  777.643333
2    2020-01-25  3045103.988  3.540127e+07  907.163  777.626667
3    2020-01-26  3045103.988  3.540127e+07  907.163  777.610000
4    2020-01-27  3045103.988  3.540127e+07  907.163  777.293333
...         ...          ...           ...      ...         ...
1566 2024-05-07  3045103.988  3.540127e+07  907.163  693.221000
1567 2024-05-08  3045103.988  3.540127e+07  907.163  693.087000
1568 2024-05-09  3045103.988  3.540127e+07  907.163  692.922000
1569 2024-05-10  3045103.988  3.540127e+07  907.163  692.788000
1570 2024-05-11  3045103.988  3.540127e+07  907.163  692.111000

[1571 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045111.715, 399697.412, 673.69)
            日期           经度          纬度      高程       水位
0   2023-04-15  3045111.715  399697.412  673.69  687.000
1   2023-04-16  3045111.715  399697.412  673.69  687.200
2   2023-04-17  3045111.715  399697.412  673.69  687.400
3   2023-04-18  3045111.715  399697.412  673.69  687.600
4   2023-04-19  3045111.715  399697.412  673.69  687.800
..         ...          ...         ...     ...      ...
388 2024-05-07  3045111.715  399697.412  673.69  635.689
389 2024-05-08  3045111.715  399697.412  673.69  635.569
390 2024-05-09  3045111.715  399697.412  673.69  635.457
391 2024-05-10  3045111.715  399697.412  673.69  635.400
392 2024-05-11  3045111.715  399697.412  673.69  635.224

[393 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045148.6737, 400730.5954, 671.68)
            日期            经度           纬度      高程       水位
0   2023-02-27  3.045149e+06  400730.5954  671.68  560.300
1   2023-02-28  3.045149e+06  400730.5954  671.68  558.500
2   2023-03-01  3.045149e+06  400730.5954  671.68  558.000
3   2023-03-02  3.045149e+06  400730.5954  671.68  557.100
4   2023-03-03  3.045149e+06  400730.5954  671.68  556.980
..         ...           ...          ...     ...      ...
435 2024-05-07  3.045149e+06  400730.5954  671.68  423.858
436 2024-05-08  3.045149e+06  400730.5954  671.68  423.737
437 2024-05-09  3.045149e+06  400730.5954  671.68  423.886
438 2024-05-10  3.045149e+06  400730.5954  671.68  423.980
439 2024-05-11  3.045149e+06  400730.5954  671.68  424.026

[440 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045230.932, 35401066.05, 907.026)
            日期           经度           纬度       高程        水位
0   2023-10-17  3045230.932  35401066.05  907.026  625.6990
1   2023-10-18  3045230.932  35401066.05  907.026  627.6680
2   2023-10-19  3045230.932  35401066.05  907.026  628.5565
3   2023-10-20  3045230.932  35401066.05  907.026  629.4450
4   2023-10-21  3045230.932  35401066.05  907.026  628.8370
..         ...          ...          ...      ...       ...
198 2024-05-02  3045230.932  35401066.05  907.026  573.9000
199 2024-05-03  3045230.932  35401066.05  907.026  573.9000
200 2024-05-04  3045230.932  35401066.05  907.026  573.9000
201 2024-05-05  3045230.932  35401066.05  907.026  573.9000
202 2024-05-06  3045230.932  35401066.05  907.026  573.9000

[203 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045315.4, 401156.7, 670.7)
           日期         经度        纬度     高程          水位
0  2024-04-06  3045315.4  401156.7  670.7  632.028000
1  2024-04-07  3045315.4  401156.7  670.7  631.001000
2  2024-04-08  3045315.4  401156.7  670.7  630.710000
3  2024-04-09  3045315.4  401156.7  670.7  630.010000
4  2024-04-10  3045315.4  401156.7  670.7  629.422000
5  2024-04-11  3045315.4  401156.7  670.7  628.817000
6  2024-04-12  3045315.4  401156.7  670.7  628.369000
7  2024-04-13  3045315.4  401156.7  670.7  627.842000
8  2024-04-14  3045315.4  401156.7  670.7  627.842000
9  2024-04-15  3045315.4  401156.7  670.7  627.842000
10 2024-04-16  3045315.4  401156.7  670.7  627.842000
11 2024-04-17  3045315.4  401156.7  670.7  627.842000
12 2024-04-18  3045315.4  401156.7  670.7  627.842000
13 2024-04-19  3045315.4  401156.7  670.7  627.842000
14 2024-04-20  3045315.4  401156.7  670.7  626.324333
15 2024-04-21  3045315.4  401156.7  670.7  624.806667
16 2024-04-22  3045315.4  401156.7  670.7  623.289000
17 2024-04-23  3045315.4  401156.7  670.7  622.805000
18 2024-04-24  3045315.4  401156.7  670.7  622.148000
19 2024-04-25  3045315.4  401156.7  670.7  621.694000
20 2024-04-26  3045315.4  401156.7  670.7  620.991000
21 2024-04-27  3045315.4  401156.7  670.7  620.568000
22 2024-04-28  3045315.4  401156.7  670.7  620.056000
23 2024-04-29  3045315.4  401156.7  670.7  619.782000
24 2024-04-30  3045315.4  401156.7  670.7  619.634000
25 2024-05-01  3045315.4  401156.7  670.7  619.235000
26 2024-05-02  3045315.4  401156.7  670.7  618.889000
27 2024-05-03  3045315.4  401156.7  670.7  619.802000
28 2024-05-04  3045315.4  401156.7  670.7  619.441000
29 2024-05-05  3045315.4  401156.7  670.7  618.821000
30 2024-05-06  3045315.4  401156.7  670.7  618.790000
31 2024-05-07  3045315.4  401156.7  670.7  618.168000
32 2024-05-08  3045315.4  401156.7  670.7  617.740000
33 2024-05-09  3045315.4  401156.7  670.7  617.292000
34 2024-05-10  3045315.4  401156.7  670.7  616.957000
35 2024-05-11  3045315.4  401156.7  670.7  616.356000
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045348.099, 398913.477, 612.32)
            日期           经度          纬度      高程        水位
0   2023-10-16  3045348.099  398913.477  612.32  609.1260
1   2023-10-17  3045348.099  398913.477  612.32  609.1280
2   2023-10-18  3045348.099  398913.477  612.32  609.1310
3   2023-10-19  3045348.099  398913.477  612.32  609.1335
4   2023-10-20  3045348.099  398913.477  612.32  609.1360
..         ...          ...         ...     ...       ...
204 2024-05-07  3045348.099  398913.477  612.32  608.0260
205 2024-05-08  3045348.099  398913.477  612.32  608.1390
206 2024-05-09  3045348.099  398913.477  612.32  608.1930
207 2024-05-10  3045348.099  398913.477  612.32  608.2660
208 2024-05-11  3045348.099  398913.477  612.32  608.2610

[209 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045444.532, 399788505.0, 611.54)
            日期           经度           纬度      高程       水位
0   2023-04-15  3045444.532  399788505.0  611.54  459.210
1   2023-04-16  3045444.532  399788505.0  611.54  459.226
2   2023-04-17  3045444.532  399788505.0  611.54  459.242
3   2023-04-18  3045444.532  399788505.0  611.54  459.258
4   2023-04-19  3045444.532  399788505.0  611.54  459.274
..         ...          ...          ...     ...      ...
388 2024-05-07  3045444.532  399788505.0  611.54  449.050
389 2024-05-08  3045444.532  399788505.0  611.54  449.035
390 2024-05-09  3045444.532  399788505.0  611.54  449.050
391 2024-05-10  3045444.532  399788505.0  611.54  449.114
392 2024-05-11  3045444.532  399788505.0  611.54  448.990

[393 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045453.7, 401240.1, 671.2)
            日期         经度        纬度     高程          水位
0   2022-12-21  3045453.7  401240.1  671.2  622.000000
1   2022-12-22  3045453.7  401240.1  671.2  621.528571
2   2022-12-23  3045453.7  401240.1  671.2  621.057143
3   2022-12-24  3045453.7  401240.1  671.2  620.585714
4   2022-12-25  3045453.7  401240.1  671.2  620.114286
..         ...        ...       ...    ...         ...
503 2024-05-07  3045453.7  401240.1  671.2  470.394000
504 2024-05-08  3045453.7  401240.1  671.2  470.046000
505 2024-05-09  3045453.7  401240.1  671.2  469.835000
506 2024-05-10  3045453.7  401240.1  671.2  469.534000
507 2024-05-11  3045453.7  401240.1  671.2  469.154000

[508 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045462.956, 35400647.754, 907.053)
            日期           经度            纬度       高程          水位
0   2023-06-28  3045462.956  3.540065e+07  907.053  640.000000
1   2023-06-29  3045462.956  3.540065e+07  907.053  639.825714
2   2023-06-30  3045462.956  3.540065e+07  907.053  639.651429
3   2023-07-01  3045462.956  3.540065e+07  907.053  639.477143
4   2023-07-02  3045462.956  3.540065e+07  907.053  639.302857
..         ...          ...           ...      ...         ...
314 2024-05-07  3045462.956  3.540065e+07  907.053  624.938000
315 2024-05-08  3045462.956  3.540065e+07  907.053  624.616000
316 2024-05-09  3045462.956  3.540065e+07  907.053  624.328000
317 2024-05-10  3045462.956  3.540065e+07  907.053  623.962000
318 2024-05-11  3045462.956  3.540065e+07  907.053  623.609000

[319 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045510.2985, 401065.2865, 670.12)
            日期            经度           纬度      高程          水位
0   2023-06-28  3.045510e+06  401065.2865  670.12  565.000000
1   2023-06-29  3.045510e+06  401065.2865  670.12  565.178571
2   2023-06-30  3.045510e+06  401065.2865  670.12  565.357143
3   2023-07-01  3.045510e+06  401065.2865  670.12  565.535714
4   2023-07-02  3.045510e+06  401065.2865  670.12  565.714286
..         ...           ...          ...     ...         ...
314 2024-05-07  3.045510e+06  401065.2865  670.12  513.852000
315 2024-05-08  3.045510e+06  401065.2865  670.12  508.411000
316 2024-05-09  3.045510e+06  401065.2865  670.12  506.234000
317 2024-05-10  3.045510e+06  401065.2865  670.12  506.055000
318 2024-05-11  3.045510e+06  401065.2865  670.12  506.605000

[319 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045651.0, 400574.9, 670.2)
             日期         经度        纬度     高程          水位
0    2020-05-28  3045651.0  400574.9  670.2  868.386000
1    2020-05-29  3045651.0  400574.9  670.2  865.176000
2    2020-05-30  3045651.0  400574.9  670.2  861.966000
3    2020-05-31  3045651.0  400574.9  670.2  861.559333
4    2020-06-01  3045651.0  400574.9  670.2  861.152667
...         ...        ...       ...    ...         ...
1438 2024-05-05  3045651.0  400574.9  670.2  611.122000
1439 2024-05-06  3045651.0  400574.9  670.2  611.100000
1440 2024-05-07  3045651.0  400574.9  670.2  611.178000
1441 2024-05-08  3045651.0  400574.9  670.2  610.613000
1442 2024-05-09  3045651.0  400574.9  670.2  610.351000

[1443 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045686.404, 400779.715, 613.93)
            日期           经度          纬度      高程       水位
0   2023-12-14  3045686.404  400779.715  613.93  631.900
1   2023-12-15  3045686.404  400779.715  613.93  628.200
2   2023-12-16  3045686.404  400779.715  613.93  617.200
3   2023-12-17  3045686.404  400779.715  613.93  617.200
4   2023-12-18  3045686.404  400779.715  613.93  678.925
..         ...          ...         ...     ...      ...
140 2024-05-02  3045686.404  400779.715  613.93  606.000
141 2024-05-03  3045686.404  400779.715  613.93  605.900
142 2024-05-04  3045686.404  400779.715  613.93  605.800
143 2024-05-05  3045686.404  400779.715  613.93  605.700
144 2024-05-06  3045686.404  400779.715  613.93  605.600

[145 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045731.833, 35400157.971, 891.566)
             日期           经度            纬度       高程       水位
0    2020-01-01  3045731.833  3.540016e+07  891.566  875.470
1    2020-01-02  3045731.833  3.540016e+07  891.566  875.420
2    2020-01-03  3045731.833  3.540016e+07  891.566  875.370
3    2020-01-04  3045731.833  3.540016e+07  891.566  875.520
4    2020-01-05  3045731.833  3.540016e+07  891.566  875.530
...         ...          ...           ...      ...      ...
1588 2024-05-07  3045731.833  3.540016e+07  891.566  887.075
1589 2024-05-08  3045731.833  3.540016e+07  891.566  887.141
1590 2024-05-09  3045731.833  3.540016e+07  891.566  887.172
1591 2024-05-10  3045731.833  3.540016e+07  891.566  887.251
1592 2024-05-11  3045731.833  3.540016e+07  891.566  887.247

[1593 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045789.476, 35401166.591, 913.439)
            日期           经度            纬度       高程       水位
0   2022-01-11  3045789.476  3.540117e+07  913.439  869.239
1   2022-01-12  3045789.476  3.540117e+07  913.439  869.201
2   2022-01-13  3045789.476  3.540117e+07  913.439  869.163
3   2022-01-14  3045789.476  3.540117e+07  913.439  869.125
4   2022-01-15  3045789.476  3.540117e+07  913.439  869.087
..         ...          ...           ...      ...      ...
847 2024-05-07  3045789.476  3.540117e+07  913.439  754.299
848 2024-05-08  3045789.476  3.540117e+07  913.439  754.299
849 2024-05-09  3045789.476  3.540117e+07  913.439  754.299
850 2024-05-10  3045789.476  3.540117e+07  913.439  754.299
851 2024-05-11  3045789.476  3.540117e+07  913.439  734.299

[852 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045833.438, 401067.686, 614.4)
            日期           经度          纬度     高程        水位
0   2023-12-14  3045833.438  401067.686  614.4  639.0000
1   2023-12-15  3045833.438  401067.686  614.4  677.6625
2   2023-12-16  3045833.438  401067.686  614.4  716.3250
3   2023-12-17  3045833.438  401067.686  614.4  646.4500
4   2023-12-18  3045833.438  401067.686  614.4  726.3000
..         ...          ...         ...    ...       ...
140 2024-05-02  3045833.438  401067.686  614.4  616.7000
141 2024-05-03  3045833.438  401067.686  614.4  616.7000
142 2024-05-04  3045833.438  401067.686  614.4  616.7000
143 2024-05-05  3045833.438  401067.686  614.4  616.7000
144 2024-05-06  3045833.438  401067.686  614.4  616.7000

[145 rows x 5 columns]
group type :  <class 'pandas.core.frame.DataFrame'>
Group: (3045947.737, 35400649.992, 911.063)
            日期           经度            纬度       高程       水位
0   2021-11-16  3045947.737  3.540065e+07  911.063  881.063
1   2021-11-17  3045947.737  3.540065e+07  911.063  880.963
2   2021-11-18  3045947.737  3.540065e+07  911.063  880.863
3   2021-11-19  3045947.737  3.540065e+07  911.063  880.763
4   2021-11-20  3045947.737  3.540065e+07  911.063  880.663
..         ...          ...           ...      ...      ...
903 2024-05-07  3045947.737  3.540065e+07  911.063  870.160

In [8]:
df_linear

              日期            经度          纬度      高程       水位
0     2023-03-31  3.044700e+06  401076.749  905.05  865.482
1     2023-04-01  3.044700e+06  401076.749  905.05  866.392
2     2023-04-02  3.044700e+06  401076.749  905.05  867.302
3     2023-04-03  3.044700e+06  401076.749  905.05  868.212
4     2023-04-04  3.044700e+06  401076.749  905.05  869.122
...          ...           ...         ...     ...      ...
15572 2024-05-07  3.045730e+09  398843.511  941.53  909.628
15573 2024-05-08  3.045730e+09  398843.511  941.53  909.774
15574 2024-05-09  3.045730e+09  398843.511  941.53  910.064
15575 2024-05-10  3.045730e+09  398843.511  941.53  910.356
15576 2024-05-11  3.045730e+09  398843.511  941.53  910.035

[15577 rows x 5 columns]

# 制作Web数据集

In [10]:
# 在第0列位置插入"序号"列，初始值为 None
df_linear.insert(0, "序号", None)
# 按索引填充序号值（如 0, 1, 2, 3...）
df_linear.loc[:, "序号"] = df_linear.index  # 通过 loc 安全赋值索引值
df_linear['日期'] = pd.to_datetime(df_linear['日期'])

In [11]:
df_linear.to_excel("./OutputData/water_level.xlsx",index=False)

In [12]:
df_linear

          序号         日期            经度          纬度      高程       水位
0          0 2023-03-31  3.044700e+06  401076.749  905.05  865.482
1          1 2023-04-01  3.044700e+06  401076.749  905.05  866.392
2          2 2023-04-02  3.044700e+06  401076.749  905.05  867.302
3          3 2023-04-03  3.044700e+06  401076.749  905.05  868.212
4          4 2023-04-04  3.044700e+06  401076.749  905.05  869.122
...      ...        ...           ...         ...     ...      ...
15572  15572 2024-05-07  3.045730e+09  398843.511  941.53  909.628
15573  15573 2024-05-08  3.045730e+09  398843.511  941.53  909.774
15574  15574 2024-05-09  3.045730e+09  398843.511  941.53  910.064
15575  15575 2024-05-10  3.045730e+09  398843.511  941.53  910.356
15576  15576 2024-05-11  3.045730e+09  398843.511  941.53  910.035

[15577 rows x 6 columns]

In [13]:
df_linear['日期'].dtype

dtype('<M8[ns]')

In [14]:
df_1 = df_linear.iloc[[0]]

In [15]:
df_1

  序号         日期           经度          纬度      高程       水位
0  0 2023-03-31  3044699.547  401076.749  905.05  865.482

In [16]:
df_1.to_excel("./OutputData/water_level_1.xlsx",index=False)